//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CerberoSendAPI
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendResult", Namespace="http://schemas.datacontract.org/2004/07/Cerbero.API")]
    public partial class SendResult : object
    {
        
        private string ErrorCodeField;
        
        private string ErrorMessageField;
        
        private string FileNameField;
        
        private string SdIIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SdIID
        {
            get
            {
                return this.SdIIDField;
            }
            set
            {
                this.SdIIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetrieveFileResult", Namespace="http://schemas.datacontract.org/2004/07/Cerbero.API")]
    public partial class RetrieveFileResult : object
    {
        
        private string CodeField;
        
        private byte[] DataField;
        
        private string ErrorCodeField;
        
        private string ErrorMessageField;
        
        private bool HasAttachmentsField;
        
        private bool HasPDFField;
        
        private string PECField;
        
        private string SdiIDField;
        
        private string SendFormatField;
        
        private System.DateTime SentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasAttachments
        {
            get
            {
                return this.HasAttachmentsField;
            }
            set
            {
                this.HasAttachmentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasPDF
        {
            get
            {
                return this.HasPDFField;
            }
            set
            {
                this.HasPDFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PEC
        {
            get
            {
                return this.PECField;
            }
            set
            {
                this.PECField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SdiID
        {
            get
            {
                return this.SdiIDField;
            }
            set
            {
                this.SdiIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SendFormat
        {
            get
            {
                return this.SendFormatField;
            }
            set
            {
                this.SendFormatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Sent
        {
            get
            {
                return this.SentField;
            }
            set
            {
                this.SentField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetrieveSentStatusResult", Namespace="http://schemas.datacontract.org/2004/07/Cerbero.API")]
    public partial class RetrieveSentStatusResult : object
    {
        
        private string ErrorCodeField;
        
        private string ErrorMessageField;
        
        private CerberoSendAPI.SentStatus[] ItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CerberoSendAPI.SentStatus[] Items
        {
            get
            {
                return this.ItemsField;
            }
            set
            {
                this.ItemsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SentStatus", Namespace="http://schemas.datacontract.org/2004/07/Cerbero.API")]
    public partial class SentStatus : object
    {
        
        private CerberoSendAPI.ErrorItem[] ErrorsField;
        
        private string FailureDescriptionField;
        
        private string FilenameField;
        
        private string SDIIDField;
        
        private string StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CerberoSendAPI.ErrorItem[] Errors
        {
            get
            {
                return this.ErrorsField;
            }
            set
            {
                this.ErrorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureDescription
        {
            get
            {
                return this.FailureDescriptionField;
            }
            set
            {
                this.FailureDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filename
        {
            get
            {
                return this.FilenameField;
            }
            set
            {
                this.FilenameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SDIID
        {
            get
            {
                return this.SDIIDField;
            }
            set
            {
                this.SDIIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorItem", Namespace="http://schemas.datacontract.org/2004/07/Cerbero.API")]
    public partial class ErrorItem : object
    {
        
        private string DescriptionField;
        
        private string IDField;
        
        private string SuggestionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Suggestion
        {
            get
            {
                return this.SuggestionField;
            }
            set
            {
                this.SuggestionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CerberoSendAPI.ISendInvoices")]
    public interface ISendInvoices
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendInvoices/Send", ReplyAction="http://tempuri.org/ISendInvoices/SendResponse")]
        System.Threading.Tasks.Task<CerberoSendAPI.SendResponse> SendAsync(CerberoSendAPI.SendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendInvoices/SendGX", ReplyAction="http://tempuri.org/ISendInvoices/SendGXResponse")]
        System.Threading.Tasks.Task<CerberoSendAPI.SendGXResponse> SendGXAsync(CerberoSendAPI.SendGXRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendInvoices/SentFileRetrieve", ReplyAction="http://tempuri.org/ISendInvoices/SentFileRetrieveResponse")]
        System.Threading.Tasks.Task<CerberoSendAPI.SentFileRetrieveResponse> SentFileRetrieveAsync(CerberoSendAPI.SentFileRetrieveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISendInvoices/RetrieveSentStatus", ReplyAction="http://tempuri.org/ISendInvoices/RetrieveSentStatusResponse")]
        System.Threading.Tasks.Task<CerberoSendAPI.RetrieveSentStatusResponse> RetrieveSentStatusAsync(CerberoSendAPI.RetrieveSentStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Send", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string APIKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string FileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public byte[] Data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public byte[] DataPdf;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Sender;
        
        public SendRequest()
        {
        }
        
        public SendRequest(string APIKey, string FileName, byte[] Data, byte[] DataPdf, string Sender)
        {
            this.APIKey = APIKey;
            this.FileName = FileName;
            this.Data = Data;
            this.DataPdf = DataPdf;
            this.Sender = Sender;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CerberoSendAPI.SendResult SendResult;
        
        public SendResponse()
        {
        }
        
        public SendResponse(CerberoSendAPI.SendResult SendResult)
        {
            this.SendResult = SendResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendGX", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendGXRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string APIKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string FileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string DataPdf;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string Sender;
        
        public SendGXRequest()
        {
        }
        
        public SendGXRequest(string APIKey, string FileName, string Data, string DataPdf, string Sender)
        {
            this.APIKey = APIKey;
            this.FileName = FileName;
            this.Data = Data;
            this.DataPdf = DataPdf;
            this.Sender = Sender;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendGXResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendGXResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CerberoSendAPI.SendResult SendGXResult;
        
        public SendGXResponse()
        {
        }
        
        public SendGXResponse(CerberoSendAPI.SendResult SendGXResult)
        {
            this.SendGXResult = SendGXResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SentFileRetrieve", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SentFileRetrieveRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string APIKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Filename;
        
        public SentFileRetrieveRequest()
        {
        }
        
        public SentFileRetrieveRequest(string APIKey, string Filename)
        {
            this.APIKey = APIKey;
            this.Filename = Filename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SentFileRetrieveResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SentFileRetrieveResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CerberoSendAPI.RetrieveFileResult SentFileRetrieveResult;
        
        public SentFileRetrieveResponse()
        {
        }
        
        public SentFileRetrieveResponse(CerberoSendAPI.RetrieveFileResult SentFileRetrieveResult)
        {
            this.SentFileRetrieveResult = SentFileRetrieveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RetrieveSentStatus", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RetrieveSentStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string APIKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] Filenames;
        
        public RetrieveSentStatusRequest()
        {
        }
        
        public RetrieveSentStatusRequest(string APIKey, string[] Filenames)
        {
            this.APIKey = APIKey;
            this.Filenames = Filenames;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RetrieveSentStatusResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RetrieveSentStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public CerberoSendAPI.RetrieveSentStatusResult RetrieveSentStatusResult;
        
        public RetrieveSentStatusResponse()
        {
        }
        
        public RetrieveSentStatusResponse(CerberoSendAPI.RetrieveSentStatusResult RetrieveSentStatusResult)
        {
            this.RetrieveSentStatusResult = RetrieveSentStatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ISendInvoicesChannel : CerberoSendAPI.ISendInvoices, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class SendInvoicesClient : System.ServiceModel.ClientBase<CerberoSendAPI.ISendInvoices>, CerberoSendAPI.ISendInvoices
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SendInvoicesClient() : 
                base(SendInvoicesClient.GetDefaultBinding(), SendInvoicesClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpsBinding_ISendInvoices.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendInvoicesClient(EndpointConfiguration endpointConfiguration) : 
                base(SendInvoicesClient.GetBindingForEndpoint(endpointConfiguration), SendInvoicesClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendInvoicesClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SendInvoicesClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendInvoicesClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SendInvoicesClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SendInvoicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<CerberoSendAPI.SendResponse> SendAsync(CerberoSendAPI.SendRequest request)
        {
            return base.Channel.SendAsync(request);
        }
        
        public System.Threading.Tasks.Task<CerberoSendAPI.SendGXResponse> SendGXAsync(CerberoSendAPI.SendGXRequest request)
        {
            return base.Channel.SendGXAsync(request);
        }
        
        public System.Threading.Tasks.Task<CerberoSendAPI.SentFileRetrieveResponse> SentFileRetrieveAsync(CerberoSendAPI.SentFileRetrieveRequest request)
        {
            return base.Channel.SentFileRetrieveAsync(request);
        }
        
        public System.Threading.Tasks.Task<CerberoSendAPI.RetrieveSentStatusResponse> RetrieveSentStatusAsync(CerberoSendAPI.RetrieveSentStatusRequest request)
        {
            return base.Channel.RetrieveSentStatusAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_ISendInvoices))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_ISendInvoices))
            {
                return new System.ServiceModel.EndpointAddress("https://cerberoapi.gxitalia.com/SendInvoices.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SendInvoicesClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpsBinding_ISendInvoices);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SendInvoicesClient.GetEndpointAddress(EndpointConfiguration.BasicHttpsBinding_ISendInvoices);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpsBinding_ISendInvoices,
        }
    }
}
